# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dpark068
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: roosevelt-island-tennis-scheduler
# "service" is the name of this project. This will also be added to your AWS resource names.
service: tennis-scheduler

provider:
  name: aws
  runtime: python3.10
  region: us-east-1  # Change the region if necessary
  environment:  # Global environment variables (optional)
    ENVIRONMENT: ${env:STAGE}
    RIOC_URL: ${env:RIOC_URL}
    USERNAME_1: ${env:USERNAME_1}
    PW_1: ${env:PW_1}
    USERNAME_2: ${env:USERNAME_2}
    PW_2: ${env:PW_2}
    USERNAME_3: ${env:USERNAME_3}
    PW_3: ${env:PW_3}
    USERNAME_4: ${env:USERNAME_4}
    PW_4: ${env:PW_4}

functions:
  rateHandler:
    timeout: 180
    handler: handler.run
    events:
      # Run every day at 8:00 AM EST/EDT
      - schedule:
          name: tennisSchedulerDaily
          description: "Run at 8:00 AM EST/EDT every day"
          enabled: true
          rate: cron(59 11 * * ? *)  # 11:59 UTC is 7:59 AM EST/EDT every day
    maximumRetryAttempts: 0  # Disable retries

# Include the serverless-python-requirements plugin
plugins:
  - serverless-python-requirements
